### ISSUE TITLE
Translation error

### ISSUE THREAD

**Issue by ibarzrm** [sitmun/sitmun-viewer-app#74]
**Describe the bug**
In Catalan version the "Draw and mesure" tool it is in Spanish. 

**To Reproduce**
1.	Click on “Tools”.
2.	See the error

**Expected behavior**
It should be “Dibuixar i medir”.

**Screenshots**
![Image](https://github.com/user-attachments/assets/11cdc6db-0ec5-419e-9fd5-884dd9a35a3e)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome 131.0.6778.267
 - Version SITMUN3 1.0

**Additional context**
The tested version is the ‘dev’ branch of SITMUN3, installed on 15 January.

**Comment by fjlopez** [comment]
Fixed. 


@ibarzrm please confirm that you can apply the update to your local host by executing in the **WLS2** terminal the following commands.

```sh
git submodule update --recursive --remote
docker compose build --no-cache front
docker compose up front -d
```

**Comment by ibarzrm** [comment]
I confirm that I have applied the update correctly by running the full sequence and the translation is applied.

```
git pull origin dev
git checkout dev
git submodule update --recursive --remote
docker compose build --no-cache front
docker compose up front -d
```

But I realised that I made a mistake, because “medir” is not correct in Catalan. It should be “mesurar”. My apologies.

**Comment by fjlopez** [comment]
Fixed. @ibarzrm please update to the last version where `medir` has been fixed. Close this issue if the labels are updated.

**Comment by ibarzrm** [comment]
I have updated the version of the "dev" branch, and it still shows "Dibuixar i _medir_".

**Comment by fjlopez** [comment]
@ibarzrm Check if the latest version `dev` version has been fetched. Using VSCode, open the folder where the `sitmun-application-stack` is and search ([Ctrl+Shift+F](https://code.visualstudio.com/docs/editor/codebasics#:~:text=VS%20Code%20allows%20you%20to%20quickly%20search%20over%20all%20files,and%20enter%20your%20search%20term.)) for the term `mesurar`. It should appear in 3 `ca-CA.json` files.

**Comment by ibarzrm** [comment]
Exactly. As you said, in VSCode there is the text ‘mesurar’ in 3 ca-CA.json files.
I have been able to verify that the correct text is already loaded. Maybe the Catalan version of the viewer was not loading correctly.

![Image](https://github.com/user-attachments/assets/a577678a-8571-4745-bc34-333549b9f9bb)

We can consider the case closed.
Thank you.
